-- ══════════════════════════════════════════════════════════════════════════
-- Anumaan — schema. Covers every entity in PRD §9, including AgentAction,
-- which is the spine of the agentic layer and must exist before any agent
-- code is written.
--
-- Idempotent: safe to re-run during the build.
-- Apply order: schema.sql, then seed.sql.
-- ══════════════════════════════════════════════════════════════════════════

-- ─── enums ────────────────────────────────────────────────────────────────

do $$ begin
  create type user_role as enum ('owner', 'staff');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Matches the prototype's state machine exactly. The only legal advance is
  -- one step forward; enforcement lives in the route handler (DET-005).
  create type order_status as enum ('new', 'preparing', 'ready', 'served');
exception when duplicate_object then null; end $$;

do $$ begin
  create type table_status as enum ('empty', 'seated', 'bill_requested', 'cleaning');
exception when duplicate_object then null; end $$;

do $$ begin
  create type queue_status as enum ('waiting', 'notified', 'seated', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  -- 'auto_executed' is reserved for the notify-only Compliance Nudge Agent.
  -- Every other agent must pass through proposed → approved | rejected.
  create type agent_action_status as enum ('proposed', 'approved', 'rejected', 'auto_executed');
exception when duplicate_object then null; end $$;

-- ─── core ─────────────────────────────────────────────────────────────────

create table if not exists restaurants (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  fssai_license text,
  upi_vpa       text,
  created_at    timestamptz not null default now()
);

-- Mirrors auth.users; `role` is the server-side source of truth for FR-A8.
create table if not exists profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  restaurant_id uuid references restaurants(id) on delete cascade,
  full_name     text,
  role          user_role not null default 'staff',
  created_at    timestamptz not null default now()
);

create table if not exists menu_items (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  name          text not null,
  category      text not null,
  veg           boolean not null default true,
  price         numeric(10, 2) not null check (price >= 0),
  available     boolean not null default true,
  description   text,
  created_at    timestamptz not null default now()
);
create index if not exists menu_items_restaurant_idx on menu_items (restaurant_id);

create table if not exists restaurant_tables (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  label         text not null,
  seats         int not null default 4,
  status        table_status not null default 'empty',
  updated_at    timestamptz not null default now(),
  unique (restaurant_id, label)
);

create table if not exists orders (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  code          text not null,                       -- human-facing id, e.g. 'O1'
  table_id      bigint references restaurant_tables(id) on delete set null,
  status        order_status not null default 'new',
  total         numeric(10, 2) not null default 0,
  paid          boolean not null default false,
  placed_at     timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (restaurant_id, code)
);
create index if not exists orders_restaurant_status_idx on orders (restaurant_id, status);

create table if not exists order_items (
  id           bigint primary key generated by default as identity,
  order_id     bigint not null references orders(id) on delete cascade,
  menu_item_id bigint references menu_items(id) on delete set null,
  name         text not null,                        -- denormalised: the bill
  qty          int not null check (qty > 0),         -- must survive menu edits
  unit_price   numeric(10, 2) not null
);
create index if not exists order_items_order_idx on order_items (order_id);

create table if not exists queue_entries (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  name          text not null,
  party_size    int not null default 2,
  phone         text,
  status        queue_status not null default 'waiting',
  joined_at     timestamptz not null default now()
);

create table if not exists inventory_items (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  name          text not null,
  stock         numeric(10, 2) not null default 0,
  max_stock     numeric(10, 2) not null default 0,
  unit          text not null default 'kg',
  low_threshold numeric(10, 2) not null default 0,
  updated_at    timestamptz not null default now()
);

create table if not exists staff_members (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  name          text not null,
  role_label    text not null,
  shift         text
);

create table if not exists customers (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  name          text not null,
  phone         text,
  visits        int not null default 0,
  last_visit_at timestamptz
);

-- Per-item daily history. This is what forecast.ts averages over — the
-- `is_synthetic` flag exists so the UI can say so out loud (PRD §10).
create table if not exists daily_summaries (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  menu_item_id  bigint not null references menu_items(id) on delete cascade,
  business_date date not null,
  qty_sold      int not null default 0,
  revenue       numeric(10, 2) not null default 0,
  is_synthetic  boolean not null default true,
  unique (restaurant_id, menu_item_id, business_date)
);
create index if not exists daily_summaries_lookup_idx
  on daily_summaries (restaurant_id, menu_item_id, business_date);

create table if not exists compliance_items (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  label         text not null,
  checked       boolean not null default false,
  checked_at    timestamptz,
  sort_order    int not null default 0
);

-- ─── the agentic spine ────────────────────────────────────────────────────

-- Every proposal writes a row here BEFORE approval, so the audit trail records
-- what was suggested even when the owner says no. Powers FR-D8 and is what the
-- trajectory evals assert against.
create table if not exists agent_actions (
  id            bigint primary key generated by default as identity,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  agent         text not null,                       -- 'Anumaan Agent', etc.
  tool_name     text,                                -- null for notify-only
  tool_args     jsonb,
  proposal      text not null,                       -- plain language, for the log
  basis         text not null,                       -- why — never optional
  status        agent_action_status not null default 'proposed',
  result_ref    text,                                -- what changed, if anything
  created_at    timestamptz not null default now(),
  resolved_at   timestamptz,
  resolved_by   uuid references auth.users(id) on delete set null
);
create index if not exists agent_actions_log_idx
  on agent_actions (restaurant_id, created_at desc);

-- Tasks pushed to the Kitchen Board once a Prep & Forecast proposal is approved.
create table if not exists prep_tasks (
  id              bigint primary key generated by default as identity,
  restaurant_id   uuid not null references restaurants(id) on delete cascade,
  agent_action_id bigint references agent_actions(id) on delete set null,
  label           text not null,
  done            boolean not null default false,
  created_at      timestamptz not null default now()
);

-- ─── row-level security ───────────────────────────────────────────────────
-- The anon key ships to the browser, so RLS is the real boundary. Customers
-- are unauthenticated by design (FR-C1: no login to browse), which is why the
-- guest-facing tables are readable by anon and the owner-facing ones are not.
-- Route handlers add the role check on top; see lib/auth.ts (DET-003).

create or replace function current_role_is(target user_role)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from profiles
    where profiles.id = auth.uid() and profiles.role = target
  );
$$;

alter table restaurants       enable row level security;
alter table profiles          enable row level security;
alter table menu_items        enable row level security;
alter table restaurant_tables enable row level security;
alter table orders            enable row level security;
alter table order_items       enable row level security;
alter table queue_entries     enable row level security;
alter table inventory_items   enable row level security;
alter table staff_members     enable row level security;
alter table customers         enable row level security;
alter table daily_summaries   enable row level security;
alter table compliance_items  enable row level security;
alter table agent_actions     enable row level security;
alter table prep_tasks        enable row level security;

do $$
declare
  guest_readable text[] := array[
    'restaurants', 'menu_items', 'restaurant_tables', 'orders',
    'order_items', 'queue_entries'
  ];
  staff_writable text[] := array[
    'menu_items', 'restaurant_tables', 'orders', 'order_items',
    'queue_entries', 'inventory_items', 'compliance_items', 'prep_tasks'
  ];
  owner_only text[] := array[
    'inventory_items', 'staff_members', 'customers',
    'daily_summaries', 'compliance_items', 'agent_actions', 'prep_tasks'
  ];
  t text;
begin
  -- Guests browse the menu, place an order, and watch its status. Nothing else.
  foreach t in array guest_readable loop
    execute format('drop policy if exists guest_read on %I', t);
    execute format('create policy guest_read on %I for select using (true)', t);
  end loop;

  execute 'drop policy if exists guest_place_order on orders';
  execute 'create policy guest_place_order on orders for insert with check (true)';
  execute 'drop policy if exists guest_place_order_items on order_items';
  execute 'create policy guest_place_order_items on order_items for insert with check (true)';
  execute 'drop policy if exists guest_join_queue on queue_entries';
  execute 'create policy guest_join_queue on queue_entries for insert with check (true)';

  -- Signed-in staff run the floor.
  foreach t in array staff_writable loop
    execute format('drop policy if exists staff_write on %I', t);
    execute format(
      'create policy staff_write on %I for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null)', t
    );
  end loop;

  -- Owner-only surfaces — the DB half of FR-A8. The route handler enforces the
  -- same rule with a 403 so the failure is legible rather than an empty list.
  foreach t in array owner_only loop
    execute format('drop policy if exists owner_read on %I', t);
    execute format(
      'create policy owner_read on %I for select to authenticated using (current_role_is(''owner''))', t
    );
  end loop;
end $$;

drop policy if exists own_profile on profiles;
create policy own_profile on profiles
  for select to authenticated using (id = auth.uid());

-- New sign-ups land in profiles automatically; the first user of a restaurant
-- is promoted to owner by seed.sql or by hand.
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    coalesce((new.raw_user_meta_data ->> 'role')::user_role, 'staff')
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();
